---

variables:
  GIT_SUBMODULE_STRATEGY: none

stages:
  - precheck
  - tests
  - deploy


########################################
# Initial checks
########################################

# Make sure there's nothing horrendously wrong first
Run pyflakes:
  stage: precheck
  image: python:3.6-alpine
  before_script:
    - pip3 install pyflakes
  script:
    - pyflakes tavern


########################################
# Unit tests
########################################

.basetest: &basetest
  stage: tests
  cache:
    key: tavern-project-cache
    paths:
      - /root/.cache/pip/
    policy: pull

  before_script:
    - pip install --upgrade tox pip setuptools
  script:
    - tox -c ${TOXCFG} -e ${CI_JOB_NAME}

  variables:
    TOXCFG: tox.ini

py27:
  <<: *basetest
  image: python:2.7-alpine

  # Make this job push the cache. It doesn't hugely matter if the cache is out
  # of date, so just do it in one job.
  cache:
    key: tavern-project-cache
    paths:
      - /root/.cache/pip/
    policy: push

py34:
  <<: *basetest
  image: python:3.4-alpine

py35:
  <<: *basetest
  image: python:3.5-alpine

py36:
  <<: *basetest
  image: python:3.6-alpine

pypy:
  <<: *basetest
  image: pypy:2-slim

pypy3:
  <<: *basetest
  image: pypy:3-slim

py27lint:
  <<: *basetest
  image: python:2.7-alpine

py36lint:
  <<: *basetest
  image: python:3.6-alpine


########################################
# Integration tests
########################################

# Different cfg file and needs docker running
.integrationtest: &inttest
  <<: *basetest
  variables:
    TOXCFG: tox-integration.ini
  services:
    - docker

py27-cookies:
  <<: *inttest
  image: python:2.7-alpine

py34-cookies:
  <<: *inttest
  image: python:3.4-alpine

py35-cookies:
  <<: *inttest
  image: python:3.5-alpine

py36-cookies:
  <<: *inttest
  image: python:3.6-alpine

pypy-cookies:
  <<: *inttest
  image: pypy:2-slim

pypy3-cookies:
  <<: *inttest
  image: pypy:3-slim


# Extra integration tests
py27-generic:
  <<: *inttest
  image: python:2.7-alpine

py36-mqtt:
  <<: *inttest
  image: python:3.6-alpine

py36-advanced:
  <<: *inttest
  image: python:3.6-alpine

py36-generic:
  <<: *inttest
  image: python:3.6-alpine
