---

variables:
  GIT_SUBMODULE_STRATEGY: none

stages:
  - precheck
  - quick-tests
  - long-tests
  - deploy


########################################
# Initial checks
# Make sure there's nothing horrendously wrong first
########################################

# Base script for tests
.basetest: &basetest
  stage: quick-tests
  cache:
    key: tavern-project-cache
    paths:
      - ./pip-cache/
    policy: pull

  before_script:
    - echo "install_command = pip install --cache-dir=./pip-cache/ {opts} {packages}" >> tox.ini
    - pip install --upgrade tox --cache-dir=./pip-cache/
  script:
    - tox -c ${TOXCFG} -e ${CI_JOB_NAME}

  variables:
    TOXCFG: tox.ini

py27flakes:
  <<: *basetest
  image: python:2.7-alpine

py37black:
  <<: *basetest
  image: python:3.7-alpine

py37:
  <<: *basetest
  image: python:3.7-alpine

py36lint:
  <<: *basetest
  image: python:3.6-alpine


########################################
# Unit tests
########################################

py27:
  <<: *basetest
  image: python:2.7-alpine

  # Make this job push the cache. It doesn't hugely matter if the cache is out
  # of date, so just do it in one job.
  cache:
    key: tavern-project-cache
    paths:
      - ./pip-cache/

pypy:
  <<: *basetest
  image: pypy:2-slim

pypy3:
  <<: *basetest
  image: pypy:3-slim

py27lint:
  <<: *basetest
  image: python:2.7-alpine


########################################
# Integration tests
########################################

# Different cfg file and needs docker running
.integrationtest: &inttest
  <<: *basetest
  stage: long-tests
  variables:
    TOXCFG: tox-integration.ini
    # DOCKER_HOST: tcp://docker:2375
  services:
    - docker:dind
  before_script:
    - pip install --upgrade docker-compose tox pip setuptools --cache-dir=./pip-cache/
    - mkdir -p /root/.docker/
    - touch /root/.docker/config.json
    - docker-compose --verbose -f ./tests/integration/docker-compose.yaml images
    - echo "install_command = pip install --cache-dir=./pip-cache/ {opts} {packages}" >> tox-integration.ini

py27-cookies:
  <<: *inttest
  image: python:2.7-alpine

py35-cookies:
  <<: *inttest
  image: python:3.5-alpine

py36-cookies:
  <<: *inttest
  image: python:3.6-alpine

pypy-cookies:
  <<: *inttest
  image: pypy:2-slim

pypy3-cookies:
  <<: *inttest
  image: pypy:3-slim


# Extra integration tests
py27-generic:
  <<: *inttest
  image: python:2.7-alpine

py36-mqtt:
  <<: *inttest
  image: python:3.6-alpine

py36-advanced:
  <<: *inttest
  image: python:3.6-alpine

py36-generic:
  <<: *inttest
  image: python:3.6-alpine
