---
sudo: false
language: python
cache: pip
matrix:
  include:
    - python: 3.3
      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=pylint
install:
  - pip install tox-travis setuptools --upgrade
# command to run tests
script:
  - tox
